## Creating Numpy Arrays

In [2]:
import numpy as np

In [3]:
#np.array
a=np.array([1,2,3])
print(a)

[1 2 3]


In [4]:
# 2d and 3d array

b=np.array([[1,2,3],[4,5,3]])
print(b)

[[1 2 3]
 [4 5 3]]


In [5]:
c=np.array([[[1,2],[3,4]],[[4,5],[6,7]]])
print(c)

[[[1 2]
  [3 4]]

 [[4 5]
  [6 7]]]


In [6]:
#dtype
np.array([1,2,0],dtype=complex)

array([1.+0.j, 2.+0.j, 0.+0.j])

In [7]:
# np.arange

np.arange(1,11,4)

array([1, 5, 9])

In [8]:
#with shape

np.arange(1,11).reshape(10,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [9]:
#np.ones and np.zeros

np.ones([3,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
np.zeros([3,4],dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [11]:
#np.random

np.random.random((3,4))

array([[0.298776  , 0.34189031, 0.82237205, 0.17248917],
       [0.86902974, 0.83624859, 0.43424914, 0.98199212],
       [0.66341492, 0.80443266, 0.07508906, 0.46828492]])

In [12]:
#np.linspace

np.linspace(-10,10,6,dtype=int)

array([-10,  -6,  -2,   2,   6,  10])

In [13]:
#np.identity

np.identity(5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

# Array attributes

In [14]:
a1=np.arange(10)
a2=np.arange(12).reshape(3,4)
a3=np.arange(1,9).reshape(2,2,2)

a3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [15]:
#ndim
a1.ndim
a2.ndim
a3.ndim

3

In [16]:
#shape

a3.shape

(2, 2, 2)

In [17]:
#itemsize

a1.itemsize

8

In [18]:
#dtype

a3.dtype

dtype('int64')

# Changing DataTypes

In [19]:
#astype

a1.astype('float32')

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

## Array operations

In [20]:
b1=np.arange(12).reshape(3,4)
b2=np.arange(12,24).reshape(3,4)
b2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [21]:
# scalar operations


#arithmatic
b1**2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [22]:
#relational

b2[b2>20]

array([21, 22, 23])

In [23]:
#vector ops
#arithmatic
b1*b2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

## Array functions

In [24]:
a4=np.random.random((3,3))
a4=np.round(a4*100)
a4

array([[82.,  2., 52.],
       [83., 67., 29.],
       [ 6., 30., 42.]])

In [25]:
# min/max/sum/prod
# 0->column
# 1->row
np.max(a4)
np.sum(a4)
np.sum(a4,axis=0)

array([171.,  99., 123.])

In [26]:
#var/std/mean/median

np.median(a4,axis=0)

array([82., 30., 42.])

In [27]:
#trig fns

np.sin(a4)

array([[ 0.31322878,  0.90929743,  0.98662759],
       [ 0.96836446, -0.85551998, -0.66363388],
       [-0.2794155 , -0.98803162, -0.91652155]])

In [28]:
#dot product

b3=np.arange(12).reshape(3,4)
b4=np.arange(12).reshape(4,3)
print(b3)
print(b4)
np.dot(b3,b4)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


array([[ 42,  48,  54],
       [114, 136, 158],
       [186, 224, 262]])

In [29]:
#log and exponents

np.log(b4)
np.exp(b4)

C:\Users\Dell\AppData\Local\Temp\ipykernel_21508\1693717817.py:3: RuntimeWarning: divide by zero encountered in log
  np.log(b4)


array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00],
       [2.00855369e+01, 5.45981500e+01, 1.48413159e+02],
       [4.03428793e+02, 1.09663316e+03, 2.98095799e+03],
       [8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

In [30]:
# round/floor/ceil
b5=np.random.random((3,3))*100
b5

array([[14.95937725, 24.1794244 , 16.3586658 ],
       [49.34509253, 45.92917283, 68.71650114],
       [86.58980259, 44.22325308,  1.51115653]])

In [31]:
np.round(b5)

array([[15., 24., 16.],
       [49., 46., 69.],
       [87., 44.,  2.]])

## Indexing and Slicing

In [38]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [67]:
a2[:,:]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [109]:
a2[0:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [107]:
a2[1,::3]

array([4, 7])

In [89]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [92]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [103]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [112]:
u=np.arange(27).reshape(3,3,3)
u[0,1,:] 

array([3, 4, 5])

In [114]:
u

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [118]:
u[::2,::3,::2]

array([[[ 0,  2]],

       [[18, 20]]])

In [113]:
u[1,:,1]

array([10, 13, 16])

In [115]:
u[2,1:,1:]

array([[22, 23],
       [25, 26]])

## Iterating on numpy

In [139]:
k=np.array([0,1,2,3,4,5,6,7,8,9])
# for i in k:
#     print(i)

def i(arr: np.array)->np.array:
    for i in arr:
        return arr

i(k)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [141]:
a2
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [143]:
for i in u:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [146]:
for i in np.nditer(a2):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


## Reshaping

In [ ]:
# reshape



In [150]:
#transpose
np.transpose(u)

array([[[ 0,  9, 18],
        [ 3, 12, 21],
        [ 6, 15, 24]],

       [[ 1, 10, 19],
        [ 4, 13, 22],
        [ 7, 16, 25]],

       [[ 2, 11, 20],
        [ 5, 14, 23],
        [ 8, 17, 26]]])

In [152]:
# ravel
u.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

## Stacking

In [153]:
# horizontal stacking

e=np.arange(12).reshape(3,4)
f=np.arange(12,24).reshape(3,4)

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [154]:
np.hstack((e,f))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [158]:
# vertical stacking

np.vstack((e,f))

dtype('int64')

In [163]:
# horizontal splitting

np.hsplit(e,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [164]:
# vertical split

np.vsplit(e,3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]